### ISSUE TITLE
Plans to support Forge?

### ISSUE THREAD

**Issue by cha0s** [PanSzelescik/proxy-protocol-support#2]
Curious if this is something you're working on. I may be able to chip away at it.

I would also appreciate any pointers if there is already a forge mod that does this for 1.18 that I'm missing!

**Comment by PanSzelescik** [comment]
For Minecraft 1.19.2 and Forge, mod is in progress. I'll try to do it later on 1.18.2

**Comment by PanSzelescik** [comment]
Sorry, but I have too many problems with loading the same mixins on Forge. That's why I decided not to release the Forge version. You can use the [shared](https://github.com/PanSzelescik/proxy-protocol-support/tree/fabric/src/main/java/pl/panszelescik/proxy_protocol_support/shared) part and try to create it yourself, I allow.
